### ISSUE TITLE
module.py file missing

### ISSUE THREAD

**Issue by IlanPrice** [IlanPrice/DCTpS#1]

**Comment by kazukiosawa** [comment]
@IlanPrice Thanks for sharing the amazing work and this repository! I'm very interested in using the DCTpS layers and would like to reproduce the results in the paper.  So I would appreciate it if you could add the `module.py` file. Thanks!

**Comment by IlanPrice** [comment]
@kazukiosawa Thanks for your interest! And apologies for the delay. An updated version of the code should be uploaded within the next week - including all currently omitted files.

**Comment by kazukiosawa** [comment]
Thanks for the quick response! Looking forward to it!

**Comment by IlanPrice** [comment]
@kazukiosawa The refactored code is now uploaded, so there shouldn't be any missing files anymore.

**Comment by kazukiosawa** [comment]
@IlanPrice Thanks for uploading the file and letting me know!
